### ISSUE TITLE
Umbau auf Dateisystem Log

### ISSUE THREAD

**Issue by baumannsven** [1601com/request-log#1]
Dieses Modul hat bei zu langen Urls Probleme die Daten in der Datenbank zu speichern. Grund ist das die Spalte der Tabelle in der Datenbank, in der die Url gespeichert wird zu klein definiert ist.
Das erwähnte Modul wird umgebaut, damit die Logs im Dateisystem anstatt in der Datenbank abgelegt werden. Wie es andere Systeme oder dergleichen auch machen.

**Comment by ps1601com** [comment]
outdated.
